### ISSUE TITLE
error msg while searching

### ISSUE THREAD

**Issue by syrius01** [MD5HashBrowns/zoomeye-search#1]
Hi!

I'm getting this error msg since only today. In the last few days everything was working fine.

sirius@blackb0x:~/ZoomEye/zoomeye-search$ python zoomeye.py -p 1000 --email email@email.com --password my-pass -s "'app:weblogic' +port:7001"
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "zoomeye.py", line 33, in <module>
    AUTH_REQUEST = requests.post(API_URL + '/user/login', data=USER_DATA)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'api.zoomeye.org' doesn't match 'api.zoomeye.org.cn'

Any help would be very appreciated.

Thanks.

**Comment by adcar** [comment]
Looks like you're on Python 2.7? I only built this script to work with Python 3.x. Make sure you have `requests` installed (`pip3 install requests`) and try running with `python3 zoomeye.py` or `./zoomeye.py`

**Comment by adcar** [comment]
Closing this due to inactivity. Feel free to reopen if you're still having this problem.
