### ISSUE TITLE
Error when launching zoomeye-search script

### ISSUE THREAD

**Issue by syrius01** [MD5HashBrowns/zoomeye-search#9]
sirius@blackb0x:~/ZoomEye/test/zoomeye-search$ python3 zoomeye.py -p 10 --email some@email.org --password my_pass -q "'Tomcat' +port:8080" -s tomcat_test.txt
[*] You have enabled save. All IPs will be saved to tomcat_test.txt
[*] Logging in as some@email.org
Traceback (most recent call last):
  File "zoomeye.py", line 229, in <module>
    main()
  File "zoomeye.py", line 218, in main
    getResult()
  File "zoomeye.py", line 164, in getResult
    TOKEN = "JWT " + getToken()
  File "zoomeye.py", line 81, in getToken
    ACCESS_TOKEN = AUTH_REQUEST.json()['access_token']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 740, in json
    return json.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by adcar** [comment]
ZoomEye appears to be throwing a`500 Internal Server Error` upon making a POST request to `/user/login`. This is still the correct API endpoint according to their documentation so I'm assuming their API is malfunctioning.

**Comment by adcar** [comment]
API is working again
